version: "3.9"

services:
  insta:
    image: maximgrinin/my_instagramm_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 5050:5000
    volumes:
      - /home/maximgrinin/pythonCW3/uploads:/code/uploads_host
